Tahub Config keys
nostrassets/Tahub.go pull request #5
Opened 2024-02-01 10:34 UTC by mubarak23

Tahub Config keys

2024-02-01 14:36 UTC, Nsandomeno commented on controllers_v2/nostr.ctrl.go
> +			c.Logger().Errorf("Failed to create user via Nostr event: %v", err)
This is not creating a user it is just providing some information to a client.

2024-02-01 14:37 UTC, Nsandomeno commented on lib/service/user.go
> +
just leave for now, we will be merging Lndhub.go and it will be good to isolate their new changes.

Down the load we will clear out everything we don't need in one PR.

2024-02-01 14:56 UTC, mubarak23 commented on controllers_v2/nostr.ctrl.go
> +			c.Logger().Errorf("Failed to create user via Nostr event: %v", err)
Am removing the checks

2024-02-01 14:57 UTC, mubarak23 commented on lib/service/user.go
> +
Alright

2024-02-02 20:44 UTC, Nsandomeno commented on controllers_v2/nostr.ctrl.go
> +	} else if body.content == "GET_SERVER_PUBKEY" {
This does not work. it is `body.Content`.

2024-02-02 20:46 UTC, Nsandomeno commented on controllers_v2/nostr.ctrl.go
> +	} else if body.content == "GET_SERVER_PUBKEY" {
Testing would have turned this up quickly, I will clean things up but please make sure you can run the previously existing functionality i.e. run the server and hit the endpoint we created.

2024-02-02 20:46 UTC, Nsandomeno requested changes
Testing would have turned this up quickly, I will clean things up but please make sure you can run the previously existing functionality i.e. run the server and hit the endpoint we created.

2024-02-02 22:08 UTC, merged